[2023-10-20T14:53:40.887+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.578248+00:00 [queued]>
[2023-10-20T14:53:40.895+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.578248+00:00 [queued]>
[2023-10-20T14:53:40.895+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-20T14:53:40.910+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-20 14:47:06.578248+00:00
[2023-10-20T14:53:40.919+0000] {standard_task_runner.py:57} INFO - Started process 5641 to run task
[2023-10-20T14:53:40.935+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-20T14:47:06.578248+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmpysdsrxgj']
[2023-10-20T14:53:40.945+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask pokelist
[2023-10-20T14:53:40.999+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.578248+00:00 [running]> on host 4662b0d5ca37
[2023-10-20T14:53:41.090+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T14:47:06.578248+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T14:47:06.578248+00:00'
[2023-10-20T14:53:41.092+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-20T14:53:41.093+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/pokelist.py']
[2023-10-20T14:53:41.108+0000] {subprocess.py:86} INFO - Output:
[2023-10-20T14:53:41.949+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-10-20T14:53:45.091+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-10-20T14:53:45.092+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-10-20T14:53:45.379+0000] {subprocess.py:93} INFO - 23/10/20 14:53:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-10-20T14:53:46.778+0000] {subprocess.py:93} INFO - 23/10/20 14:53:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2023-10-20T14:53:46.782+0000] {subprocess.py:93} INFO - 23/10/20 14:53:46 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2023-10-20T14:53:46.783+0000] {subprocess.py:93} INFO - 23/10/20 14:53:46 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2023-10-20T14:55:31.229+0000] {subprocess.py:93} INFO - ERROR:root:Exception while sending command.
[2023-10-20T14:55:31.234+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:55:31.234+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 516, in send_command
[2023-10-20T14:55:31.235+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2023-10-20T14:55:31.236+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2023-10-20T14:55:31.236+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:55:31.237+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:55:31.237+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:55:31.238+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:55:31.238+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2023-10-20T14:55:31.238+0000] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2023-10-20T14:55:31.239+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 539, in send_command
[2023-10-20T14:55:31.239+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2023-10-20T14:55:31.239+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-10-20T14:55:31.239+0000] {subprocess.py:93} INFO - A Requisição de nº 1 coletou 50 Pokemons
[2023-10-20T14:55:31.239+0000] {subprocess.py:93} INFO - A Requisição de nº 2 coletou 50 Pokemons
[2023-10-20T14:55:31.241+0000] {subprocess.py:93} INFO - A Requisição de nº 3 coletou 50 Pokemons
[2023-10-20T14:55:31.241+0000] {subprocess.py:93} INFO - A Requisição de nº 4 coletou 50 Pokemons
[2023-10-20T14:55:31.241+0000] {subprocess.py:93} INFO - A Requisição de nº 5 coletou 50 Pokemons
[2023-10-20T14:55:31.242+0000] {subprocess.py:93} INFO - A Requisição de nº 6 coletou 50 Pokemons
[2023-10-20T14:55:31.242+0000] {subprocess.py:93} INFO - A Requisição de nº 7 coletou 50 Pokemons
[2023-10-20T14:55:31.242+0000] {subprocess.py:93} INFO - A Requisição de nº 8 coletou 50 Pokemons
[2023-10-20T14:55:31.242+0000] {subprocess.py:93} INFO - A Requisição de nº 9 coletou 50 Pokemons
[2023-10-20T14:55:31.242+0000] {subprocess.py:93} INFO - A Requisição de nº 10 coletou 50 Pokemons
[2023-10-20T14:55:31.242+0000] {subprocess.py:93} INFO - A Requisição de nº 11 coletou 50 Pokemons
[2023-10-20T14:55:31.243+0000] {subprocess.py:93} INFO - A Requisição de nº 12 coletou 50 Pokemons
[2023-10-20T14:55:31.243+0000] {subprocess.py:93} INFO - A Requisição de nº 13 coletou 50 Pokemons
[2023-10-20T14:55:31.243+0000] {subprocess.py:93} INFO - A Requisição de nº 14 coletou 50 Pokemons
[2023-10-20T14:55:31.243+0000] {subprocess.py:93} INFO - A Requisição de nº 15 coletou 50 Pokemons
[2023-10-20T14:55:31.243+0000] {subprocess.py:93} INFO - A Requisição de nº 16 coletou 50 Pokemons
[2023-10-20T14:55:31.244+0000] {subprocess.py:93} INFO - A Requisição de nº 17 coletou 50 Pokemons
[2023-10-20T14:55:31.245+0000] {subprocess.py:93} INFO - A Requisição de nº 18 coletou 50 Pokemons
[2023-10-20T14:55:31.245+0000] {subprocess.py:93} INFO - A Requisição de nº 19 coletou 50 Pokemons
[2023-10-20T14:55:31.256+0000] {subprocess.py:93} INFO - A Requisição de nº 20 coletou 50 Pokemons
[2023-10-20T14:55:31.256+0000] {subprocess.py:93} INFO - A Requisição de nº 21 coletou 50 Pokemons
[2023-10-20T14:55:31.256+0000] {subprocess.py:93} INFO - A Requisição de nº 22 coletou 50 Pokemons
[2023-10-20T14:55:31.256+0000] {subprocess.py:93} INFO - A Requisição de nº 23 coletou 50 Pokemons
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO - A Requisição de nº 24 coletou 50 Pokemons
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO - A Requisição de nº 25 coletou 50 Pokemons
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO - A Requisição de nº 26 coletou 42 Pokemons
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/pokelist.py", line 41, in <module>
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO -     df_pokes = ss.read.json(df_pokes)
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 440, in json
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(jrdd))
[2023-10-20T14:55:31.257+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2023-10-20T14:55:31.258+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2023-10-20T14:55:31.258+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2023-10-20T14:55:31.258+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2023-10-20T14:55:31.258+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/protocol.py", line 334, in get_return_value
[2023-10-20T14:55:31.258+0000] {subprocess.py:93} INFO -     raise Py4JError(
[2023-10-20T14:55:31.258+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o27.json
[2023-10-20T14:55:33.244+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-20T14:55:33.393+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-20T14:55:33.492+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=pokelist, execution_date=20231020T144706, start_date=20231020T145340, end_date=20231020T145533
[2023-10-20T14:55:33.886+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 83 for task pokelist (Bash command failed. The command returned a non-zero exit code 1.; 5641)
[2023-10-20T14:55:34.131+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T14:55:34.257+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
