[2023-10-20T14:46:38.585+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:46:35.599230+00:00 [queued]>
[2023-10-20T14:46:38.605+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:46:35.599230+00:00 [queued]>
[2023-10-20T14:46:38.616+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-20T14:46:38.653+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-20 14:46:35.599230+00:00
[2023-10-20T14:46:38.666+0000] {standard_task_runner.py:57} INFO - Started process 2599 to run task
[2023-10-20T14:46:38.680+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-20T14:46:35.599230+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmp3u880_e0']
[2023-10-20T14:46:38.701+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask pokelist
[2023-10-20T14:46:38.797+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-20T14:46:35.599230+00:00 [running]> on host 4662b0d5ca37
[2023-10-20T14:46:38.984+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T14:46:35.599230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T14:46:35.599230+00:00'
[2023-10-20T14:46:38.987+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-20T14:46:38.988+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/pokelist.py']
[2023-10-20T14:46:39.018+0000] {subprocess.py:86} INFO - Output:
[2023-10-20T14:46:40.864+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-10-20T14:46:48.238+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-10-20T14:46:48.251+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-10-20T14:46:49.103+0000] {subprocess.py:93} INFO - 23/10/20 14:46:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-10-20T14:46:52.645+0000] {subprocess.py:93} INFO - 23/10/20 14:46:52 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2023-10-20T14:46:52.688+0000] {subprocess.py:93} INFO - 23/10/20 14:46:52 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2023-10-20T14:46:52.689+0000] {subprocess.py:93} INFO - 23/10/20 14:46:52 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2023-10-20T14:46:52.689+0000] {subprocess.py:93} INFO - 23/10/20 14:46:52 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2023-10-20T14:46:52.689+0000] {subprocess.py:93} INFO - 23/10/20 14:46:52 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2023-10-20T14:46:52.691+0000] {subprocess.py:93} INFO - 23/10/20 14:46:52 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2023-10-20T14:47:26.289+0000] {subprocess.py:93} INFO - 23/10/20 14:47:26 ERROR Inbox: Ignoring error
[2023-10-20T14:47:26.291+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2023-10-20T14:47:26.292+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2023-10-20T14:47:26.292+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2023-10-20T14:47:26.292+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2023-10-20T14:47:26.293+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2023-10-20T14:47:26.293+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2023-10-20T14:47:26.294+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
[2023-10-20T14:47:26.294+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
[2023-10-20T14:47:26.295+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
[2023-10-20T14:47:26.295+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
[2023-10-20T14:47:26.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
[2023-10-20T14:47:26.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
[2023-10-20T14:47:26.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
[2023-10-20T14:47:26.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2023-10-20T14:47:26.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2023-10-20T14:47:26.301+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2023-10-20T14:47:26.301+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2023-10-20T14:47:26.302+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2023-10-20T14:47:26.302+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-10-20T14:47:26.302+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-10-20T14:47:26.302+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-10-20T14:47:26.303+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@4662b0d5ca37:39623
[2023-10-20T14:47:26.303+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
[2023-10-20T14:47:26.303+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
[2023-10-20T14:47:26.304+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[2023-10-20T14:47:26.304+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[2023-10-20T14:47:26.305+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.305+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
[2023-10-20T14:47:26.307+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
[2023-10-20T14:47:26.307+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.307+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.308+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.310+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.311+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete(Promise.scala:53)
[2023-10-20T14:47:26.311+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[2023-10-20T14:47:26.311+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[2023-10-20T14:47:26.311+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2023-10-20T14:47:26.311+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.312+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
[2023-10-20T14:47:26.312+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
[2023-10-20T14:47:26.312+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.312+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.313+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.313+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.313+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete(Promise.scala:53)
[2023-10-20T14:47:26.313+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[2023-10-20T14:47:26.314+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[2023-10-20T14:47:26.314+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2023-10-20T14:47:26.314+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.315+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
[2023-10-20T14:47:26.315+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
[2023-10-20T14:47:26.315+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2023-10-20T14:47:26.315+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
[2023-10-20T14:47:26.316+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
[2023-10-20T14:47:26.316+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
[2023-10-20T14:47:26.316+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
[2023-10-20T14:47:26.317+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
[2023-10-20T14:47:26.317+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
[2023-10-20T14:47:26.317+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
[2023-10-20T14:47:26.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
[2023-10-20T14:47:26.318+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
[2023-10-20T14:47:26.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
[2023-10-20T14:47:26.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
[2023-10-20T14:47:26.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
[2023-10-20T14:47:26.319+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete(Promise.scala:53)
[2023-10-20T14:47:26.320+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[2023-10-20T14:47:26.321+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[2023-10-20T14:47:26.321+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.success(Promise.scala:86)
[2023-10-20T14:47:26.321+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.success$(Promise.scala:86)
[2023-10-20T14:47:26.322+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
[2023-10-20T14:47:26.322+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
[2023-10-20T14:47:26.322+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
[2023-10-20T14:47:26.322+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
[2023-10-20T14:47:26.322+0000] {subprocess.py:93} INFO - 	... 8 more
[2023-10-20T14:47:26.322+0000] {subprocess.py:93} INFO - 23/10/20 14:47:26 WARN Executor: Issue communicating with driver in heartbeater
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2023-10-20T14:47:26.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2023-10-20T14:47:26.324+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2023-10-20T14:47:26.325+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2023-10-20T14:47:26.326+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2023-10-20T14:47:26.326+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2023-10-20T14:47:26.326+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
[2023-10-20T14:47:26.326+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
[2023-10-20T14:47:26.326+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2023-10-20T14:47:26.327+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - 	... 3 more
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@4662b0d5ca37:39623
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[2023-10-20T14:47:26.328+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.329+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
[2023-10-20T14:47:26.329+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
[2023-10-20T14:47:26.329+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.329+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.330+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.330+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.330+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete(Promise.scala:53)
[2023-10-20T14:47:26.330+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[2023-10-20T14:47:26.330+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[2023-10-20T14:47:26.331+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2023-10-20T14:47:26.331+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.345+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete(Promise.scala:53)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
[2023-10-20T14:47:26.346+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
[2023-10-20T14:47:26.347+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
[2023-10-20T14:47:26.348+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
[2023-10-20T14:47:26.348+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
[2023-10-20T14:47:26.348+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2023-10-20T14:47:26.349+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
[2023-10-20T14:47:26.349+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
[2023-10-20T14:47:26.349+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[2023-10-20T14:47:26.350+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
[2023-10-20T14:47:26.350+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
[2023-10-20T14:47:26.351+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
[2023-10-20T14:47:26.351+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete(Promise.scala:53)
[2023-10-20T14:47:26.351+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[2023-10-20T14:47:26.352+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[2023-10-20T14:47:26.352+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.success(Promise.scala:86)
[2023-10-20T14:47:26.354+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Promise.success$(Promise.scala:86)
[2023-10-20T14:47:26.354+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
[2023-10-20T14:47:26.355+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
[2023-10-20T14:47:26.366+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
[2023-10-20T14:47:26.367+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
[2023-10-20T14:47:26.367+0000] {subprocess.py:93} INFO - 	... 8 more
[2023-10-20T14:48:58.638+0000] {subprocess.py:93} INFO - A Requisição de nº 1 coletou 50 Pokemons
[2023-10-20T14:48:58.668+0000] {subprocess.py:93} INFO - A Requisição de nº 2 coletou 50 Pokemons
[2023-10-20T14:48:58.668+0000] {subprocess.py:93} INFO - A Requisição de nº 3 coletou 50 Pokemons
[2023-10-20T14:48:58.668+0000] {subprocess.py:93} INFO - A Requisição de nº 4 coletou 50 Pokemons
[2023-10-20T14:48:58.668+0000] {subprocess.py:93} INFO - A Requisição de nº 5 coletou 50 Pokemons
[2023-10-20T14:48:58.668+0000] {subprocess.py:93} INFO - A Requisição de nº 6 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 7 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 8 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 9 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 10 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 11 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 12 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 13 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 14 coletou 50 Pokemons
[2023-10-20T14:48:58.669+0000] {subprocess.py:93} INFO - A Requisição de nº 15 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 16 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 17 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 18 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 19 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 20 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 21 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 22 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - A Requisição de nº 23 coletou 50 Pokemons
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:48:58.670+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
[2023-10-20T14:48:58.697+0000] {subprocess.py:93} INFO -     conn = connection.create_connection(
[2023-10-20T14:48:58.715+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
[2023-10-20T14:48:58.715+0000] {subprocess.py:93} INFO -     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[2023-10-20T14:48:58.715+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
[2023-10-20T14:48:58.715+0000] {subprocess.py:93} INFO -     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2023-10-20T14:48:58.715+0000] {subprocess.py:93} INFO - socket.gaierror: [Errno -3] Temporary failure in name resolution
[2023-10-20T14:48:58.716+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:48:58.716+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:48:58.716+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:48:58.716+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:48:58.725+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2023-10-20T14:48:58.726+0000] {subprocess.py:93} INFO -     httplib_response = self._make_request(
[2023-10-20T14:48:58.726+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2023-10-20T14:48:58.726+0000] {subprocess.py:93} INFO -     self._validate_conn(conn)
[2023-10-20T14:48:58.726+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2023-10-20T14:48:58.726+0000] {subprocess.py:93} INFO -     conn.connect()
[2023-10-20T14:48:58.727+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
[2023-10-20T14:48:58.727+0000] {subprocess.py:93} INFO -     self.sock = conn = self._new_conn()
[2023-10-20T14:48:58.728+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO -     raise NewConnectionError(
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0bb442acd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:48:58.797+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO -     resp = conn.urlopen(
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO -     retries = retries.increment(
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO -     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pokeapi.co', port=443): Max retries exceeded with url: /api/v2/pokemon/?offset=1150&limit=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0bb442acd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:48:58.798+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/pokelist.py", line 29, in <module>
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -     response = requests.get(url)
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -     return request("get", url, params=params, **kwargs)
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -     return session.request(method=method, url=url, **kwargs)
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
[2023-10-20T14:48:58.799+0000] {subprocess.py:93} INFO -     resp = self.send(prep, **send_kwargs)
[2023-10-20T14:48:58.800+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
[2023-10-20T14:48:58.877+0000] {subprocess.py:93} INFO -     r = adapter.send(request, **kwargs)
[2023-10-20T14:48:58.877+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
[2023-10-20T14:48:58.877+0000] {subprocess.py:93} INFO -     raise ConnectionError(e, request=request)
[2023-10-20T14:48:58.877+0000] {subprocess.py:93} INFO - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pokeapi.co', port=443): Max retries exceeded with url: /api/v2/pokemon/?offset=1150&limit=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0bb442acd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-10-20T14:49:01.103+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-20T14:49:01.164+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-20T14:49:01.175+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=pokelist, execution_date=20231020T144635, start_date=20231020T144638, end_date=20231020T144901
[2023-10-20T14:49:01.222+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 66 for task pokelist (Bash command failed. The command returned a non-zero exit code 1.; 2599)
[2023-10-20T14:49:01.242+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T14:49:01.345+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
