[2023-10-20T14:53:28.051+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.445941+00:00 [queued]>
[2023-10-20T14:53:28.067+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.445941+00:00 [queued]>
[2023-10-20T14:53:28.068+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-20T14:53:28.096+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-20 14:47:06.445941+00:00
[2023-10-20T14:53:28.104+0000] {standard_task_runner.py:57} INFO - Started process 5315 to run task
[2023-10-20T14:53:28.117+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-20T14:47:06.445941+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmpnpptpcvc']
[2023-10-20T14:53:28.122+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask pokelist
[2023-10-20T14:53:28.193+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.445941+00:00 [running]> on host 4662b0d5ca37
[2023-10-20T14:53:28.288+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T14:47:06.445941+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T14:47:06.445941+00:00'
[2023-10-20T14:53:28.291+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-20T14:53:28.292+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/pokelist.py']
[2023-10-20T14:53:28.309+0000] {subprocess.py:86} INFO - Output:
[2023-10-20T14:53:29.419+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-10-20T14:53:33.864+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-10-20T14:53:33.865+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-10-20T14:53:34.337+0000] {subprocess.py:93} INFO - 23/10/20 14:53:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-10-20T14:54:32.677+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 4) / 4]                                                                                ----------------------------------------
[2023-10-20T14:54:32.686+0000] {subprocess.py:93} INFO - Exception occurred during processing of request from ('127.0.0.1', 38224)
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO - ERROR:root:Exception while sending command.
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 516, in send_command
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:54:32.687+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:54:32.688+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:54:32.688+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:54:32.688+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2023-10-20T14:54:32.688+0000] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2023-10-20T14:54:32.688+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 539, in send_command
[2023-10-20T14:54:32.689+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2023-10-20T14:54:32.689+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-10-20T14:54:32.689+0000] {subprocess.py:93} INFO - A Requisição de nº 1 coletou 50 Pokemons
[2023-10-20T14:54:32.690+0000] {subprocess.py:93} INFO - A Requisição de nº 2 coletou 50 Pokemons
[2023-10-20T14:54:32.690+0000] {subprocess.py:93} INFO - A Requisição de nº 3 coletou 50 Pokemons
[2023-10-20T14:54:32.690+0000] {subprocess.py:93} INFO - A Requisição de nº 4 coletou 50 Pokemons
[2023-10-20T14:54:32.690+0000] {subprocess.py:93} INFO - A Requisição de nº 5 coletou 50 Pokemons
[2023-10-20T14:54:32.691+0000] {subprocess.py:93} INFO - A Requisição de nº 6 coletou 50 Pokemons
[2023-10-20T14:54:32.692+0000] {subprocess.py:93} INFO - A Requisição de nº 7 coletou 50 Pokemons
[2023-10-20T14:54:32.692+0000] {subprocess.py:93} INFO - A Requisição de nº 8 coletou 50 Pokemons
[2023-10-20T14:54:32.692+0000] {subprocess.py:93} INFO - A Requisição de nº 9 coletou 50 Pokemons
[2023-10-20T14:54:32.692+0000] {subprocess.py:93} INFO - A Requisição de nº 10 coletou 50 Pokemons
[2023-10-20T14:54:32.692+0000] {subprocess.py:93} INFO - A Requisição de nº 11 coletou 50 Pokemons
[2023-10-20T14:54:32.692+0000] {subprocess.py:93} INFO - A Requisição de nº 12 coletou 50 Pokemons
[2023-10-20T14:54:32.693+0000] {subprocess.py:93} INFO - A Requisição de nº 13 coletou 50 Pokemons
[2023-10-20T14:54:32.693+0000] {subprocess.py:93} INFO - A Requisição de nº 14 coletou 50 Pokemons
[2023-10-20T14:54:32.693+0000] {subprocess.py:93} INFO - A Requisição de nº 15 coletou 50 Pokemons
[2023-10-20T14:54:32.693+0000] {subprocess.py:93} INFO - A Requisição de nº 16 coletou 50 Pokemons
[2023-10-20T14:54:32.693+0000] {subprocess.py:93} INFO - A Requisição de nº 17 coletou 50 Pokemons
[2023-10-20T14:54:32.693+0000] {subprocess.py:93} INFO - A Requisição de nº 18 coletou 50 Pokemons
[2023-10-20T14:54:32.694+0000] {subprocess.py:93} INFO - A Requisição de nº 19 coletou 50 Pokemons
[2023-10-20T14:54:32.694+0000] {subprocess.py:93} INFO - A Requisição de nº 20 coletou 50 Pokemons
[2023-10-20T14:54:32.694+0000] {subprocess.py:93} INFO - A Requisição de nº 21 coletou 50 Pokemons
[2023-10-20T14:54:32.694+0000] {subprocess.py:93} INFO - A Requisição de nº 22 coletou 50 Pokemons
[2023-10-20T14:54:32.696+0000] {subprocess.py:93} INFO - A Requisição de nº 23 coletou 50 Pokemons
[2023-10-20T14:54:32.696+0000] {subprocess.py:93} INFO - A Requisição de nº 24 coletou 50 Pokemons
[2023-10-20T14:54:32.696+0000] {subprocess.py:93} INFO - A Requisição de nº 25 coletou 50 Pokemons
[2023-10-20T14:54:32.696+0000] {subprocess.py:93} INFO - A Requisição de nº 26 coletou 42 Pokemons
[2023-10-20T14:54:32.697+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:54:32.697+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/pokelist.py", line 50, in <module>
[2023-10-20T14:54:32.698+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:54:32.707+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
[2023-10-20T14:54:32.710+0000] {subprocess.py:93} INFO -     self.process_request(request, client_address)
[2023-10-20T14:54:32.710+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
[2023-10-20T14:54:32.712+0000] {subprocess.py:93} INFO -     self.finish_request(request, client_address)
[2023-10-20T14:54:32.712+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
[2023-10-20T14:54:32.712+0000] {subprocess.py:93} INFO -     self.RequestHandlerClass(request, client_address, self)
[2023-10-20T14:54:32.712+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
[2023-10-20T14:54:32.712+0000] {subprocess.py:93} INFO -     self.handle()
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/accumulators.py", line 295, in handle
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -     poll(accum_updates)
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/accumulators.py", line 267, in poll
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -     if self.rfile in r and func():
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/accumulators.py", line 271, in accum_updates
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -     num_updates = read_int(self.rfile)
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/serializers.py", line 596, in read_int
[2023-10-20T14:54:32.713+0000] {subprocess.py:93} INFO -     raise EOFError
[2023-10-20T14:54:32.718+0000] {subprocess.py:93} INFO - EOFError
[2023-10-20T14:54:32.719+0000] {subprocess.py:93} INFO - ----------------------------------------
[2023-10-20T14:54:32.719+0000] {subprocess.py:93} INFO -     df_pokes.write.parquet(
[2023-10-20T14:54:32.719+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
[2023-10-20T14:54:32.719+0000] {subprocess.py:93} INFO -     self._jwrite.parquet(path)
[2023-10-20T14:54:32.719+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2023-10-20T14:54:32.719+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2023-10-20T14:54:32.731+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2023-10-20T14:54:32.734+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2023-10-20T14:54:32.735+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/protocol.py", line 334, in get_return_value
[2023-10-20T14:54:32.735+0000] {subprocess.py:93} INFO -     raise Py4JError(
[2023-10-20T14:54:32.735+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o62.parquet
[2023-10-20T14:54:33.928+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-20T14:54:34.057+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-20T14:54:34.131+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=pokelist, execution_date=20231020T144706, start_date=20231020T145328, end_date=20231020T145434
[2023-10-20T14:54:34.266+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 81 for task pokelist (Bash command failed. The command returned a non-zero exit code 1.; 5315)
[2023-10-20T14:54:34.340+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T14:54:34.432+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
